version: '3'


services:
  db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - db-data:/data/db
    networks:
      - db-network
    ports:
      - "27017:27017"

  app:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    networks:
      - db-network
    ports:
      - "5000:5000"
    volumes:
      - .:/code

volumes:
  db-data:

networks:
  db-network:
